# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBnxet():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bnxet(self):
    self.driver.get("https://bonbanh.com/khanh-hoa/oto")
    self.driver.set_window_size(782, 823)
    self.driver.find_element(By.CSS_SELECTOR, ".car-item:nth-child(1) .h-car-img").click()
    self.driver.execute_script("window.scrollTo(0,100)")
    self.driver.find_element(By.CSS_SELECTOR, ".car-item:nth-child(6) .cb6_02").click()
    self.driver.find_element(By.CSS_SELECTOR, ".car-item:nth-child(18) .cb6_02").click()
    self.driver.find_element(By.CSS_SELECTOR, ".car-item:nth-child(20) .h-car-img").click()
    self.driver.execute_script("window.scrollTo(0,100)")
    self.driver.execute_script("window.scrollTo(0,0)")
  
